# Generated by Django 4.0 on 2022-04-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glucoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result1', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucoses', to='auth.user')),
            ],
            options={
                'verbose_name': 'pomiar cukru',
                'verbose_name_plural': 'pomiary cukru',
            },
        ),
        migrations.CreateModel(
            name='Bloodpressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result1', models.IntegerField(blank=True, null=True)),
                ('result2', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodpressures', to='auth.user')),
            ],
            options={
                'verbose_name': 'ciśnienie',
                'verbose_name_plural': 'ciśnienia',
            },
        ),
    ]
